CREATE TABLE PERSON (
  ID   NUMERIC AUTO_INCREMENT,
  NAME NVARCHAR2(100),
  AGE  NUMERIC
);

INSERT INTO PERSON (NAME, AGE) VALUES ('John', 20);
INSERT INTO PERSON (NAME, AGE) VALUES ('John', 21);
INSERT INTO PERSON (NAME, AGE) VALUES ('Bill', 30);
